### ISSUE TITLE
Don't have your issues in your project

### ISSUE THREAD

**Issue by ericadamski** [kathryngauthier/simple-chat-app#5]
@assem-el-merhi @sidd0043 @kathryngauthier, you guys did almost everything except put the issues into the project. Please do that. Also your milestone is already overdue, it should be set to Feb 1st.

**Comment by assem-el-merhi** [comment]
Hi Eric I added our issues into the project but if I were to update the milestone does Kathryn have to do that because she created the milestone or can I create it.

**Comment by assem-el-merhi** [comment]
Never mind I updated the date, thank you for messaging us Eric have a great weekend.

**Comment by ericadamski** [comment]
💯
